### ISSUE TITLE
Question: Integrate Scala.js for missing objects?

### ISSUE THREAD

**Issue by tobilg** [henridf/apache-spark-node#10]
I just stumbled over [Scala.js](https://github.com/scala-js/scala-js), and asked myself if parts of it's code could be used to provide missing JS objects like `Seq` or others...

**Comment by henridf** [comment]
I don't think scala.js is of help here, due to the difference in architectures (scala.js is about compile-time, source-level "binding" of js and scala, and we're about runtime binding of js and jvm bytecode).

But if you run into anything more specific of interest, please post.
