### ISSUE TITLE
Adding external JARs

### ISSUE THREAD

**Issue by tobilg** [henridf/apache-spark-node#11]
I was trying to access the `spark-csv` [package](https://github.com/databricks/spark-csv), but I was unsuccessful by either 

a) Adding it to the `java.classpath` like

    java.classpath.push("/tmp/jarCache/spark-csv_2.10-1.3.0.jar");

b) Specifying the `--jar` parameter in the `args` for 'NodeSparkSubmit'

Is there a suggested way to do this that I am missing?

**Comment by tobilg** [comment]
Nevermind, found the answer by supplying the `--packages` argument like this

```
args = ['--class', 'org.apache.spark.repl.Main', '--packages', 'com.databricks:spark-csv_2.10:1.3.0']
           .concat(['spark-shell']);
```

and supplying the SparkContext with the JAR via `addJar()` like this: `sparkContext.addJar()`

Maybe it would make sense to add this to the Readme...

**Comment by henridf** [comment]
> Maybe it would make sense to add this to the Readme...

Indeed... PR welcome :)

(bonus points for providing a short example of using the package...)

**Comment by steptaker10** [comment]
tobilg 
i need yr help
i need to create facebook api group post comment fetch
i will pay u for this job
pls
contact handa10@gmail.com
thanks

**Comment by tobilg** [comment]
@steptaker10 What in the world has the Facebook API to do with this issue? Look at the docs at https://developers.facebook.com/docs/graph-api/reference/v2.5/group#read and build it yourself.

**Comment by henridf** [comment]
@tobilg actually re the first part, you should be able to pass `--packages 'com.databricks:spark csv_2.10:1.3.0'`  on the command line rather than having to modify `args` in the file. Let me know if that doesn't work.

**Comment by tobilg** [comment]
That's correct if you use if from the command line. As I integrated it into another application, I will need to use the `args` array I guess. The passign of the packages can be dynamic, I just wrote it statically to show the behavior.
