### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by henridf** [henridf/apache-spark-node#14]
To make it easy to get started (for those who don't have a local installation of Spark and/or node)

**Comment by tobilg** [comment]
I can take care of this. Any preference concerning the distribution?

**Comment by henridf** [comment]
That would be great!

I'm unexperienced when it comes to dockerfiles, but my guess would be to start off from an existing spark or node dockerfile, which means going with whatever distribution that is using (likely standard ubuntu). 

Does this make sense?

**Comment by tobilg** [comment]
Afaik there's no official Spark image. As it has more dependencies than Node, I'd suggest to start with a Java/Ubuntu base image, and add Node.js later on.

**Comment by tobilg** [comment]
Another question is what you expect to be started with the Docker image start. I guess it's `bin/spark-node`? If so, the Docker container can be used interactively by supplying `docker -i ...` which would then start the Spark-Node REPL...

**Comment by henridf** [comment]
Starting `bin/spark-node` makes sense to me.

**Comment by tobilg** [comment]
Good. I think I can finish this tomorrow.

**Comment by tobilg** [comment]
I launched an automated build with the Docker Hub at https://hub.docker.com/r/tobilg/spark-node/

**Comment by henridf** [comment]
I'm assuming the "Full Description" section on the Docker Hub page doesn't automatically update with the readme from the repo? If that assumption is correct, I'd recommend changing it to a (briefer) description of the Docker image itself, with a pointer to the GitHub repo.
(Plus things like the "Requirements" section of the readme don't make sense on the Docker Hub page anyway).

**Comment by tobilg** [comment]
Actually, it does auto-update. I'd suggest that you open an account yourself, then you're flexible to change it like you want.

**Comment by henridf** [comment]
Are you saying I can modify the "Full Description" on `
https://hub.docker.com/r/tobilg/spark-node/`? I have an account but I don't
see a way to do that.

**Comment by tobilg** [comment]
You can only do that if you're the owner of the image. That's why I'm suggesting you should create your own image. I'll retract my image then.

**Comment by henridf** [comment]
Ah, thanks, that makes sense.

**Comment by henridf** [comment]
Created image under my docker hub account as per @tobilg's suggestion and pointed README.md to it.

**Comment by henridf** [comment]
Closing this issue. Thanks @tobilg !

**Comment by tobilg** [comment]
What I noted is that I'm still stated as maintainer of the Docker image, and that the description on the Docker Hub is empty. Just to let you know...

**Comment by henridf** [comment]
Docker Hub description filled.

Re the maintainer in the Dockerfile, I left you as a way to acknowledge that you're the author. 

But I could just as well put myself as maintainer and leave a comment right next to it naming you as the original author. What do you prefer?
