### ISSUE TITLE
Integration of external packages with inheritance on existing classes

### ISSUE THREAD

**Issue by tobilg** [henridf/apache-spark-node#15]
In the case of the [Elasticsearch Spark plugin](https://github.com/elastic/elasticsearch-hadoop#apache-spark), the `SparkContext` is amended with additional methods, such as `esRDD()` and `makeRDD()`.

I wasn't yet successful in using this plugin, because it's not really clear to me how to add the external classes in this case.

With the Spark CSV plugin, this seems to be no issue.

**Comment by tobilg** [comment]
Any idea on how to tackle this?

**Comment by henridf** [comment]
I haven't had time to dig into how the ES spark plugin works, but to get started, how about using the java API? ( `var esapi = java.import('org.elasticsearch.spark.rdd.api.java.JavaEsSpark')` )
