### ISSUE TITLE
Failure at installation

### ISSUE THREAD

**Issue by yashgt** [henridf/apache-spark-node#23]
e:\Projects\apache-spark-node\node_modules\java>if not defined npm_config_node_g
yp (node "D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_
modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: incorrect header check
gyp ERR! stack     at Zlib._handle.onerror (zlib.js:366:17)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd e:\Projects\apache-spark-node\node_modules\java
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\\\node.exe" "D:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! java@0.6.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.6.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the java package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls java
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     e:\Projects\apache-spark-node\npm-debug.log

**Comment by tobilg** [comment]
On Windows, there are known problems which are related to node-gyp, see https://github.com/joeferner/node-java/issues/280 

This is not something this project can fix IMHO.I'm having the same problems myself, but on Mac OS X and Linux everything compiles smoothly.

**Comment by henridf** [comment]
Thanks for jumping in and diagnosing @tobilg. 
I've updated the README to mention currently working platforms (Linux and OS X).
