### ISSUE TITLE
Question: Is it somehow possible to use a Context and execute statements in parallel?

### ISSUE THREAD

**Issue by tobilg** [henridf/apache-spark-node#25]
I was trying to reuse an existing Context, und run some statements in parallel.

As it seems, this is not possible due to the nature of `node-java`. I opened an issue at https://github.com/joeferner/node-java/issues/290 but have not received a definitive answer yet.

As the Spark docs say,

> multiple parallel jobs can run simultaneously if they were submitted from separate threads

which I didn't find a solution for, yet. Do you have any idea?

**Comment by henridf** [comment]
Good question. I can't think of a good way to do this with the current implementation. 

That said, this is something I'd been thinking about as one of the possible next enhancements to the library... concurrency needs to be supported and made easy by this library. An obvious use case would be a node rest api server using this library to start/manager spark jobs. (As an aside, I'd be curious to know your use case if you can share). 

Created issues #26 and #27 for this work.

**Comment by tobilg** [comment]
Actually, I have created a REST API server which is working quite nicely. Unfortunately I can't OpenSource it currently because it was created for my employer. But I'm planning on disussing this, and hopefully find a solution. 

As of the node-java docs I tend to think it's impossible to leverage Java threads for this purpose, see 

* https://github.com/joeferner/node-java#javaNewProxy

I did some tests, and even when using the Java thread classes the calls are still synchronous. This is aus well documented in the link above. 

I couldn't find another solution yet unfortunately.

**Comment by henridf** [comment]
I saw your question on node-java and looked into `javaNewProxy` but I think that proxies are a red herring here - maybe due to the unfortunate choice of `Thread` in the example of the node-java docs.

My guess is that it should be possible to leverage threads (following something like https://github.com/joeferner/node-java/issues/290#issuecomment-168677983). If you can share your tests where you used the Java thread classes but still had synchronous calls, that would be very helpful.

**Comment by tobilg** [comment]
Maybe I misunderstood this... But I don't think Joe's answer really solves my problem, because the thread would need to run the JS Spark code, and I don't see how this can work within a Java class.

I'll try to make some Gists out of my trials, but this will be difficult because I used my own abstractions of the Spark context.

**Comment by tobilg** [comment]
Regarding the REST API Server, I'm in discussions with my colleagues and superiors. Hopefully I can reach a decision next week.

**Comment by tobilg** [comment]
Fixed in https://github.com/henridf/apache-spark-node/issues/27
