### ISSUE TITLE
unionAll not working?

### ISSUE THREAD

**Issue by liebrand** [henridf/apache-spark-node#34]
Hi there; perhaps I'm misunderstanding how this should work, but shouldn't the below code simply create a union of the two data sets and output the count? Instead I'm getting a java.lang.NullPointerException on the unionAll call?

    var spark = require('apache-spark-node');
    var context = spark([], process.env.ASSEMBLY_JAR);
    var sqlContext = context.sqlContext;
    var sqlFunctions = context.sqlFunctions;

    var data1 = [
      {"name":"Michael"},
      {"name":"Andy", "age":30},
      {"name":"Justin", "age": 19}
    ];

    var data2 = [
      {"name":"Fiona"},
      {"name":"Jenny", "age":30},
      {"name":"Sandra", "age":30},
      {"name":"Alexa", "age": 19}
    ];

    var df1 = sqlContext.createDataFrame(data1);
    var df2 = sqlContext.createDataFrame(data2);

    console.log(df1.countSync());
    console.log(df2.countSync());

    var u = df1.unionAll(df2);
    console.log(u.countSync());

**Comment by henridf** [comment]
Thanks for the report! Your code is just fine and you ran into a bug that's being fixed over in #35.

**Comment by henridf** [comment]
Pushed fixed version 0.3.3 to NPM.
