### ISSUE TITLE
Problem with spark-node

### ISSUE THREAD

**Issue by pola88** [henridf/apache-spark-node#36]
Hi guys,

I installed via npm into my project and I downloaded the spark-assembly, but when I try to run spark-node I get the following error:

Command:
```
ASSEMBLY_JAR=/Users/pola/spark-test/bin/spark-assembly-1.6.0-hadoop2.6.0.jar node_modules/apache-spark-node/bin/spark-node
```

Error:

```
/Users/pola/spark-test/node_modules/apache-spark-node/js/functions.js:3
true; if ("value" in descriptor) descriptor.writable = true; Object.defineProp
                                                                    ^
TypeError: Cannot redefine property: length
    at Function.defineProperty (native)
    at defineProperties (/Users/pola/spark-test/node_modules/apache-spark-node/js/functions.js:3:296)
    at /Users/pola/spark-test/node_modules/apache-spark-node/js/functions.js:3:495
    at /Users/pola/spark-test/node_modules/apache-spark-node/js/functions.js:33:5
    at Object.<anonymous> (/Users/pola/spark-test/node_modules/apache-spark-node/js/functions.js:2415:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

What am I missing?

I am using:
```
apache-spark-node: 0.3.3
node: v0.10.28
```

Thanks in advance,
PoLa

**Comment by pola88** [comment]
I upgraded the node version, but I am still getting the error.

**Comment by henridf** [comment]
@pola88 what is the upgraded node version you tried with? And did you get the same error message?

**Comment by henridf** [comment]
Hmm, actually I just tried running with node 0.12.7 and I get the same error as you. Not sure when that broke as I initially developed with 0.12 (as noted in the README which is now incorrect).

I've recently been using 4.x which works fine. I'd suggest using that for the time being. 

I'll keep this issue open to look into the 0.12 breakage.

**Comment by pola88** [comment]
Thanks @henridf , I have upgraded to 0.12.7 as noted in the README and I still get the same error message.

Changing the name of a function (```length``` in lib/functions.js:1317) it works.

When I require the package in my node project, I must to pass an empty string as argument and also I got an error from Java, but I can use it anyway.

```
import ApacheSparkNode from 'apache-spark-node';

let apacheSparkNode = ApacheSparkNode('');
let df = apacheSparkNode.sqlContext.read().jsonSync('/Users/pola/spark-test/data/people.json');
```

The error Java is:

```
ERROR SparkContext: Error adding jar (java.lang.IllegalArgumentException: /Users/pola/spark-test cannot be a directory.), was the --addJars option used?
```

Thanks in advance,
PoLa.
