### ISSUE TITLE
Would you like the "spark" module name on npm?

### ISSUE THREAD

**Issue by dmiddlecamp** [henridf/apache-spark-node#40]
Hi @henridf !

  David from Particle here, we used to have "spark", but I think it makes sense for you guys to have it.  Thoughts?

Thanks!
David

**Comment by henridf** [comment]
Hi David, Thanks for reaching out!
Is this for the 'spark' GitHub org? If so I think that might be useful as
an organization for spark-related projects, of which this could be one.

**Comment by dmiddlecamp** [comment]
Hi @henridf ,

  Although we might eventually part with the spark org name, at the moment I was just thinking about the "spark" module name on npm if you think that might be a good fit for this project.  

Thanks!
David

**Comment by henridf** [comment]
Ah I see, that makes a lot more sense actually. In that case yes, I would
definitely be interested. What would be the next step?  My email is
username@gmail.com if nec. Thanks again! Henri
