### ISSUE TITLE
Read data from mysql

### ISSUE THREAD

**Issue by alex5o2** [henridf/apache-spark-node#44]
Hello is possible read data from mysql ?

Regards.

**Comment by henridf** [comment]
Sure, you can read data from mysql with node. 

Can you be more specific about what you are trying to accomplish?

**Comment by alex5o2** [comment]
I need read data from mysql and process this data end export a json file from front-end.
In the documentation (https://henridf.github.io/apache-spark-node/DataFrameReader.html) I see 2 option: from json or text.

For example in python have this:
`df = sqlContext.load(source="jdbc", url="jdbc:mysql://localhost:3306/test?user=root&password=password", dbtable="people")`

Thanks

**Comment by henridf** [comment]
I haven't used the jdbc source with mysql, but I'm not aware of any reason why it wouldn't work. Have you tried this?

**Comment by alex5o2** [comment]
I did not try at the moment, but I will try.

**Comment by henridf** [comment]
no further response, was unclear to begin with, closing. @alex5o2 please re-open with detailed/reproducible steps if you have further issues.
