### ISSUE TITLE
df.toJSON() not working

### ISSUE THREAD

**Issue by tobilg** [henridf/apache-spark-node#5]
I try to get a DataFrame as a JSON structure via `df.toJSON()`. The command completes, but the output is

````
spark-node> var df = sqlContext.read().json("./data/people.json")
spark-node> df.toJSON()
nodeJava_org_apache_spark_rdd_MapPartitionsRDD {
  'org$apache$spark$rdd$RDD$$evidence$1': nodeJava_scala_reflect_ClassTag__anon_1 {} }
spark-node> 
````

Is it possible to get a DataFrame as JSON with the current version?

**Comment by henridf** [comment]
As described [here](http://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.sql.DataFrame), `DataFrame.toJSON()` returns an RDD, which probably isn't what you want. 

You can get the dataframe back into the shell by doing `df.collect()`. This will give you an array of strings that you can then convert to JSON using `JSON.parse()`

**Comment by tobilg** [comment]
Thanks, `df.toJSON().collect()` does what I want. I was basically confused about the RDD creation's output.
